### ISSUE TITLE
error when expanding the output

### ISSUE THREAD

**Issue by dasigna** [creame/elementor-datepicker-localization#1]
great work, but sadly not that perfect yet.

if changing the date output via functions to show the full name of the month or the name of the day of the week in addition, the form throws format errors.

further on it would be really nice if the time picker could be set to 24h format too without further tweaking.

thanks for the work.

**Comment by pacotole** [comment]
Hi @dasigna!

Form validation is fixed in version 1.1.0. Also added a filter to use 24h time format.

Thanks for your feedback.

**Comment by dasigna** [comment]
stunning! seems to work like a charm ...

thanks :)

EDIT:
ahhh - sorry, wait... form throws an error for time field already upon page load and claims wanting an input. set a placeholder of 'desired time', but that doesnt seem to be the issue - it appears if this is a demanded field.
