### ISSUE TITLE
How to use elementor datepicker localization?

### ISSUE THREAD

**Issue by Remiol** [creame/elementor-datepicker-localization#3]
Glad I found your plugin.

I have a multi language site.
I have installed and activated your plugin "elementor-datepicker-localization" in the plugin directory.
My datapicker should be in french (my locale = french) but it is still in english (mm / dd / yyyy).
Also my time is still in 12 hour format.

What did I do wrong?

**Comment by Remiol** [comment]
Any idea?

**Comment by pacotole** [comment]
Hi!

Out of the box the plugin only localize Elementor datepicker with the site defined language.
To change date format you need to add some php code in your theme `functions.php`:

```php
// Change date format to dd/mm/yyyy
add_filter( 'elementor/datepicker/format', function(){ return 'd/m/Y'; } );

// Use 24h format on time input
add_filter( 'elementor/datepicker/24h', '__return_true' );
```

**Comment by Remiol** [comment]
Thank you very much.
It works fine. 🙂
